/**
 * @fileoverview The visitor keys for the new and updated node types
 * @author Michał Sajnóg <https://github.com/michalsnik>
 * MIT License
 */

"use strict";

const Evk = require("eslint-visitor-keys");

module.exports = Evk.unionWith({
    ArrayPattern: ["typeAnnotation"],
    ArrowFunctionExpression: ["returnType", "typeParameters"],
    AssignmentPattern: ["typeAnnotation"],
    CallExpression: ["typeParameters"],
    ClassDeclaration: ["superTypeParameters", "typeParameters"],
    ClassExpression: ["superTypeParameters", "typeParameters"],
    ClassImplements: ["typeParameters"],
    ClassProperty: ["typeAnnotation"],
    FunctionDeclaration: ["returnType"],
    FunctionExpression: ["returnType", "typeParameters"],
    Identifier: ["typeAnnotation"],
    InterfaceDeclaration: ["typeParameters"],
    NewExpression: ["typeParameters"],
    ObjectPattern: ["typeAnnotation"],
    RestElement: ["typeAnnotation"],
    TaggedTemplateExpression: ["typeParameters"],
    VariableDeclarator: ["typeParameters"],

    TSAbstractClassProperty: ["typeAnnotation", "key", "value"],
    TSAbstractKeyword: [],
    TSAbstractMethodDefinition: ["key", "value"],
    TSAnyKeyword: [],
    TSArrayType: [],
    TSAsyncKeyword: [],
    TSBooleanKeyword: [],
    TSConstructorType: ["typeAnnotation"],
    TSConstructSignature: ["typeAnnotation", "typeParameters"],
    TSDeclareKeyword: [],
    TSEnumDeclaration: ["members"],
    TSEnumMember: ["initializer"],
    TSExportAssignment: ["expression"],
    TSExportKeyword: [],
    TSImportType: ["parameter", "qualifier", "typeParameters"],
    TSLiteralType: [],
    TSIndexSignature: ["typeAnnotation", "index"],
    TSInterfaceBody: ["body"],
    TSInterfaceDeclaration: ["body", "id", "heritage"],
    TSInterfaceHeritage: ["id", "typeParameters"],
    TSFunctionType: ["typeAnnotation"],
    TSMethodSignature: ["typeAnnotation", "typeParameters", "key", "params"],
    TSModuleBlock: ["body"],
    TSModuleDeclaration: ["id", "body"],
    TSNamespaceFunctionDeclaration: [],
    TSNonNullExpression: [],
    TSNeverKeyword: [],
    TSNullKeyword: [],
    TSNumberKeyword: [],
    TSObjectKeyword: [],
    TSParameterProperty: ["parameter"],
    TSPrivateKeyword: [],
    TSPropertySignature: ["typeAnnotation", "key", "initializer"],
    TSProtectedKeyword: [],
    TSPublicKeyword: [],
    TSQualifiedName: ["left", "right"],
    TSQuestionToken: [],
    TSReadonlyKeyword: [],
    TSStaticKeyword: [],
    TSStringKeyword: [],
    TSSymbolKeyword: [],
    TSTypeAnnotation: ["typeAnnotation"],
    TSTypeLiteral: [],
    TSTypeOperator: ["typeAnnotation"],
    TSTypeParameter: ["constraint", "default"],
    TSTypeParameterDeclaration: ["params"],
    TSTypeParameterInstantiation: ["params"],
    TSTypePredicate: ["typeAnnotation", "parameterName"],
    TSTypeReference: ["typeName", "typeParameters"],
    TSUnionType: [],
    TSUndefinedKeyword: [],
    TSVoidKeyword: []
});
